project:
  type: website
  output-dir: _site

website:
  title: "Anurag Ranjak"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: index.qmd
        text: Notes

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
    math-method: mathjax
