---
title: "Mathematical descriptions of classic and modern Hopfield networks."
toc: true
toc-depth: 3
number-sections: true
format:
  pdf:
    latex-engine: xelatex
    geometry: margin=2.5cm
    fontsize: 11pt
    linestretch: 1.15
    colorlinks: true
    documentclass: scrartcl
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
    toc-title: "Contents"
    page-layout: full
    code-copy: true
    smooth-scroll: true
    anchor-sections: true
    math-method: mathjax
---

Hopfield Networks as Models of Emergent Function in Biology

## Mathematical descriptions of classic and modern Hopfield networks.
a system that discriminates *but* noise & signal
geometric operation that projects onto subspace
gradient-like dynamics on a landscape.

## Applications of Hopfield network.
all variants of Hopfield are a common underlying logic

(i) Dynamical update for the state of the system
(ii) a set of stored patterns that act as attractors.

(a) $\vec{x}(t) = \{ x_1(t) \ldots x_N(t) \}$ ← spins or neurons.

(b) $\mathcal{E}_{\text{int}} \equiv P \times N$; where $P = \#$ of patterns
In spin glasses the patterns are often assumed to be random and independent, but in many biophysics the patterns will be correlated.

(c) An update rule or differential equation governing the dynamics
e.g. $x_i(t+1) = f_i(\vec{x}(t))$ for discrete time.
or $\frac{dx_i}{dt} = f_i(\vec{x}(t)) - x_i$ for continuous time.
$f_i$ are chosen such that all $P$ patterns are fixed points when the no. of patterns is sufficiently small compared to $N$.

(d) A $P$-dimensional order parameter $m(t) = (m_1(t) \ldots m_P(t))$ which measures alignment of $\vec{x}(t)$ at time $t$ with each of the stored patterns $P$.

(e) A energy function, Lyapunov which decreases with time as a result of the update rule.
